[package]
name = "crush"
version = "0.1.0"
authors = ["Axel Liljencrantz <liljencrantz@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "A command line shell that is also a powerful and modern programming language"
readme = "README.md"
repository = "https://github.com/liljencrantz/crush"

[build-dependencies.prost-build]
version = "0.6.1"

[build-dependencies.lalrpop]
version = "0.18.1"
features = ["lexer"]

[workspace]
members = [
    "signature",
    "ordered_map",
]

[dependencies.signature]
path = "signature"

[dependencies.ordered_map]
path = "ordered_map"

[dependencies]
lalrpop-util = "0.18.1"
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
rustyline = "5.0.3"
users = "0.9.1"
dirs = "1.0.5"
serde_json = "1.0"
toml = "0.5.6"
reqwest = { version = "0.10", features = ["blocking"] }
crossbeam = "0.7"
time = "0.1.40"
prost = "0.6"
bytes = "0.5.4"
termion = "1.5.5"
float-ord = "0.2.0"
maplit = "1.0.2"
ssh2 = "0.8.2"
rand = "0.7.3"
sys-info = "0.7.0"
battery = "0.7.5"
nix = "0.17.0"

[target.'cfg(target_os = "linux")'.dependencies]
psutil = "3.1.0"
dbus = "0.8.4"
roxmltree = "0.13.0"
systemd = "0.4.0"
